# Generated by Django 5.0.1 on 2024-03-04 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_request_room_staff_proof_slot_request_slot_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='registration_number',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
